var giocatori = [
["acunzo nicola", 2],
["adelizzi cosimo", 2],
["aiello davide", 2],
["aiello piera", 2],
["alaimo roberta", 2],
["albano lucia", 2],
["alemanno maria soave", 2],
["amitrano alessandro", 2],
["andreuzza giorgia", 2],
["angelucci antonio", 2],
["angiola nunzio", 2],
["annibali lucia", 2],
["anzaldi michele", 2],
["aprea valentina", 2],
["aprile nadia", 2],
["aresta giovanni luca", 2],
["ascani anna", 2],
["ascari stefania", 2],
["avossa eva", 2],
["azzolina lucia", 2],
["badole mirco", 2],
["bagnasco roberto", 2],
["baldelli simone", 2],
["baldini maria teresa", 2],
["baldino vittoria", 2],
["baratto raffaele", 2],
["barbuto elisabetta maria", 2],
["barelli paolo", 3],
["baroni anna lisa", 2],
["baroni massimo enrico", 2],
["bartolozzi giusi", 2],
["barzotti valentina", 2],
["basin giuseppe", 2],
["battelli sergio", 2],
["battilocchio alessandro", 2],
["bazoli alfredo", 2],
["bazzaro alex", 2],
["bella marco", 2],
["bellachioma giuseppe ercole", 2],
["bellucci maria teresa", 2],
["belotti daniele", 2],
["benamati gianluca", 2],
["bendinelli davide", 2],
["benedetti silvia", 2],
["benigni stefano", 2],
["benvenuto alessandro manuel", 2],
["berardini fabio", 2],
["bergamini deborah", 2],
["berlinghieri marina", 2],
["bersani pier luigi", 2],
["berti francesco", 2],
["bianchi matteo luigi", 2],
["biancofiore michaela", 2],
["bignami galeazzo", 2],
["billi simone", 2],
["bilotti anna", 2],
["binelli diego", 2],
["bisa ingrid", 2],
["bitonci massimo", 2],
["[boccia francesco", 2],
["boldi rossana", 2],
["boldrini laura", 2],
["bologna fabiola", 2],
["bonafede alfonso", 2],
["bond dario", 2],
["boniardi fabio massimo", 2],
["bonomo francesca", 2],
["bordo michele", 2],
["bordonali simona", 2],
["borghese mario alejandro", 2],
["borghi claudio", 2],
["borghi enrico", 2],
["boschi maria elena", 3],
["braga chiara", 2],
["brambilla michela vittoria", 2],
["brescia giuseppe", 2],
["bruno raffaele", 2],
["bruno bossio vincenza", 2],
["bubisutti aurelia", 2],
["bucalo carmela", 2],
["buffagni stefano", 2],
["buompane giuseppe", 2],
["buratti umberto", 2],
["businarolo francesca", 2],
["butti alessio", 2],
["cabras pino", 2],
["cadeddu luciano", 2],
["caffaratto gualtiero", 2],
["caiata salvatore", 2],
["calabria annagrazia", 2],
["campana micaela", 2],
["cancelleri azzurra pia maria", 2],
["cannatelli pasquale", 2],
["cannizzaro francesco", 2],
["cantalamessa gianluca", 2],
["cantini laura", 2],
["cantone carla", 2],
["cantone luciano", 2],
["caon roberto", 2],
["caparvi virginio", 2],
["capitanio massimiliano", 2],
["cappellacciugo", 2],
["cappellani santi", 2],
["carabetta luca", 2],
["carbonaro alessandra", 2],
["cardinale daniela", 2],
["care' nicola", 2],
["carelli emilio", 2],
["caretta maria cristina", 2],
["carinelli paola", 2],
["carnevali elena", 2],
["carrara maurizio", 2],
["casa vittoria", 2],
["casciello luigi", 2],
["casino michele", 2],
["caso andrea", 2],
["cassese gianpaolo", 2],
["cassinelli roberto", 2],
["castelli laura", 2],
["castiello giuseppina", 2],
["casu andrea", 2],
["cataldi roberto", 2],
["cattaneo alessandro", 2],
["cattoi maurizio", 2],
["cattoi vanessa", 2],
["cavandoli laura", 2],
["ceccanti stefano", 2],
["cecchetti fabrizio", 2],
["cecconi andrea", 2],
["cenni susanna", 2],
["centemero giulio", 2],
["cestari emanuele", 2],
["chiazzese giuseppe", 2],
["ciaburro monica", 2],
["ciaga' graziella levla", 2],
["ciampi lucia", 2],
["cillis luciano", 2],
["cimino rosalba", 2],
["ciprinitiziana", 2],
["cirielli edmondo", 2],
["coin dimitri", 2],
["colaninno matteo", 2],
["colla jari", 2],
["colletti andrea", 2],
["colmellere angela", 2],
["colucci alessandro", 2],
["comaroli silvan andreina", 2],
["comencini vito", 2],
["cominardi claudio", 2],
["conte federico", 2],
["corda emanuela", 2],
["cornel valentina", 2],
["cortelazzo piergiorgio", 2],
["costa enrico", 2],
["costanzo jessica", 2],
["covolo silvia", 2],
["crippa andrea", 3],
["crippa davide", 3],
["cristina mirella", 2],
["critelli francesco", 2],
["cubeddu sebastiano", 2],
["cunial sara", 2],
["curro' giovanni", 2],
["daga federica", 2],
["d'alessandro camillo", 2],
["dall'osso matteo", 2],
["dal moro gian pietro", 2],
["d'ambrosio giuseppe", 2],
["dara andrea", 2],
["d'arrando celeste", 2],
["d'attis mauro", 2],
["/ de angelis sara", 2],
["de carlo sabrina", 2],
["de filippo vito", 2],
["de giorgi rosalba", 2],
["de girolamo carlo ügo", 2],
["deiana paola", 2],
["deidda salvatore", 2],
["del barba mauro", 2],
["del basso de caro umberto", 2],
["del grosso daniele", 2],
["d'elia cecilia", 2],
["della frera guido", 2],
["delmastro delle vedove andrea", 2],
["del monaco antonio", 2],
["de lorenzis diego", 2],
["de lorenzo rina", 2],
["delrio graziano", 2],
["del sesto margherita", 2],
["de luca piero", 2],
["de maria andrea", 2],
["de martini guido", 2],
["de menech roger", 2],
["de micheli paola", 2],
["d'eramo luigi", 2],
["de toma massimiliano", 2],
["d'ettore felice maurizio", 2],
["dieni federica", 2],
["di giorgi rosa maria", 2],
["dilauro carmen", 2],
["di maio marco", 2],
["di muro flavio", 2],
["d'ippolito giuseppe", 2],
["di san martino lorenzato di ivrea luis", 2],
["roberto", 2],
["di sarno gianfranco", 2],
["di stasio iolanda", 2],
["di stefano manlio", 2],
["donina giuseppe cesare", 2],
["donno leonardo", 2],
["donzelli giovanni", 2],
["dori devis", 2],
["d'orso valentina", 2],
["durigon claudio", 2],
["d'uva francesco", 2],
["ehm yana chiara", 2],
["emiliozzi mirella", 2],
["ermellino alessandra", 2],
["fantinati mattia", 2],
["fantuz marica", 2],
["faro marialuisa", 2],
["fascina marta antonia", 2],
["fassina stefano", 2],
["fassino piero", 2],
["fatuzzo carlo", 2],
["federico antonio", 2],
["ferraili marzia", 2],
["ferraresi vittorio", 2],
["ferrari roberto paolo", 2],
["ferri cosimo maria", 2],
["ferro wanda", 2],
["fiano emanuele", 2],
["ficara paolo", 2],
["fico roberto", 2],
["fioramonti lorenzo", 2],
["fiorini benedetta", 2],
["fitzgerald nissoli fucsia", 2],
["fl.ati francesca", 2],
["fogliani ketty", 2],
["fontana gregorio", 2],
["fontana ilaria", 2],
["fontana lorenzo", 2],
["forciniti francesco", 2],
["formentini paolo", 2],
["fornaro federico", 3],
["foscolo sara", 2],
["i foti tommaso", 2],
["fraccaro riccardo", 2],
["fragomeli gian mario", 2],
["frailis andrea", 2],
["frassinetti paola", 2],
["frassini rebecca", 2],
["frate flora", 2],
["fregolent silvia", 2],
["frusone luca", 2],
["furgiuele domenico", 2],
["fusacchia alessandro", 2],
["gadda maria chiara", 2],
["gagliardi manuela", 2],
["gagnarli chiara", 2],
["galantino davide", 2],
["galizia francesca", 2],
["galli dario", 2],
["gallinella filippo", 2],
["gallo luigi", 2],
["gariglio davide", 2],
["gastaldi flavio", 2],
["gava vannia", 2],
["gebhard renate", 2],
["gemmato marcello", 2],
["gentile andrea", 2],
["gerardi francesca", 2],
["germana' antonino", 2],
["giaccone andrea", 2],
["giachetti roberto", 2],
["giacometti antonietta", 2],
["giacometto carlo", 2],
["giacomoni sestino", 2],
["giannone veronica", 2],
["giarrizzo andrea", 2],
["giglio vigna alessandro", 2],
["giordano conny", 2],
["giorgis andrea", 2],
["giuliano carla", 2],
["giuliodori paolo", 2],
["gobbato claudia", 2],
["golinelli guglielmo", 2],
["grande marta", 2],
["gribaudo chiara", 2],
["grillo giulia", 2],
["grimaldi nicola", 2],
["grimoldi paolo", 2],
["grippa carmela", 2],
["gubitosa michele", 2],
["gusmeroli alberto luigi", 2],
["ianaro angela", 2],
["iezzi igor giancarlo", 2],
["incerti antonella", 2],
["invernizzi cristian", 2],
["invidia niccolo'", 2],
["iorio marianna", 2],
["iovino luigi", 2],
["l'abbate giuseppe", 2],
["labriola vincenza", 2],
["lacarra marco", 2],
["la marca francesca", 2],
["lapia mara", 2],
["lattanzio paolo", 2],
["lazzarini arianna", 2],
["legnaioli donatella", 2],
["lepri stefano", 2],
["librandi gianfranco", 2],
["licatini caterina", 2],
["liuni marzio", 2],
["liuzzi mirella", 2],
["lolini mario", 2],
["lollobrigida francesco", 3],
["lombardo antonio", 2],
["lo monte carmelo", 2],
["longo fausto", 2],
["lorefice marialucia", 2],
["lorenzin beatrice", 2],
["lorenzoni eva", 2],
["lorenzoni gabriele", 2],
["losacco alberto", 2],
["loss martina", 2],
["lotti luca", 2],
["lovecchio giorgio", 2],
["lucaselli ylenja", 2],
["lucchini elena", 2],
["lucentini mauro", 2],
["maccanti elena", 2],
["macina anna", 2],
["madia maria anna", 2],
["maggioni marco", 2],
["magi riccardo", 2],
["maglione pasquale", 2],
["mammi' stefania", 2],
["manca alberto", 2],
["manca gavino", 2],
["mancini claudio", 2],
["mandelli andrea", 2],
["maniero alvise", 2],
["mantovani lucrezia maria benedetta", 2],
["manzato franco", 2],
["manzo teresa", 2],
["maraia generoso", 2],
["marattin luigi", 2],
["marchetti ricardo augusto", 2],
["mariani felice", 2],
["marin marco", 3],
["marino bernardo", 2],
["marrocco patrizia", 2],
["martinciglio vita", 2],
["martin antonio", 2],
["marzana maria", 2],
["maschio ciro", 2],
["masi angela", 2],
["maturi filippo", 2],
["mauri matteo", 2],
["mazzetti erica", 2],
["melicchio alessandro", 2],
["melilli fabio", 2],
["menga rosa", 2],
["miceli carmelo", 2],
["micheli matteo", 2],
["micillo salvatore", 2],
["migliore gennaro", 2],
["migliorino luca", 2],
["milanato lorena", 2],
["minardo antonino", 2],
["misiti carmelo massimo", 2],
["molinari riccardo", 3],
["mollicone federico", 2],
["molten nicola", 2],
["montaruli augusta", 2],
["mor mattia", 2],
["morani alessia", 2],
["morassut roberto", 2],
["morelli alessandro", 2],
["moretto sara", 2],
["morgoni mario", 2],
["morrone jacopo", 2],
["moschioni daniele", 2],
["mugnai stefano", 2],
["mule' giorgio", 2],
["mura romina", 2],
["murelli elena", 2],
["muroni rossella", 2],
["musella graziano", 2],
["napoli osvaldo", 2],
["nappi silvana", 2],
["nardi martina", 2],
["navarra pietro", 2],
["nesci dalila", 2],
["nevi raffaele", 2],
["nitti michele", 2],
["nobili luciano", 2],
["noja lisa", 2],
["novelli roberto", 2],
["occhionero giuseppina", 2],
["olgiati riccardo", 2],
["orfini matteo", 2],
["orrico anna laura", 2],
["orsini andrea", 2],
["osnato marco", 2],
["pagani alberto", 2],
["pagan alessandro", 2],
["pagano ubaldo", 2],
["paita raffaella", 2],
["palazzotto erasmo", 2],
["pallini maria", 2],
["palmier antonio", 2],
["palmisano valentina", 2],
["panizzut massimiliano", 2],
["paolin giuseppe", 2],
["paolini luca rodolfo", 2],
["papiro antonella", 2],
["parentela paolo", 2],
["parisse martina", 2],
["parolo ugo", 2],
["pastorino luca", 2],
["patassini tullio", 2],
["patelli cristina", 2],
["paternoster paolo", 2],
["paxia maria laura", 2],
["pedrazzini claudio", 2],
["pella roberto", 2],
["pellicani nicola", 2],
["penna leonardo salvatore", 2],
["pentangelo antonio", 2],
["perantoni mario", 2],
["perconti filippo giuseppe", 2],
["perego di cremnago matteo", 2],
["pettarin guido germano", 2],
["pettazzi lino", 2],
["pezzopane stefania", 2],
["piastra carlo", 2],
["picchi guglielmo", 2],
["piccoli nardelli flavia", 2],
["piccolo tiziana", 2],
["pignatone dedalo cosimo gaetano", 2],
["pini giuditta", 2],
["pittalis pietro", 2],
["pizzetti luciano", 2],
["plangger albrecht", 2],
["polidori catia", 2],
["pollastrini barbara", 2],
["polverini renata", 2],
["porchietto claudia", 2],
["portas giacomo", 2],
["potenti manfredi", 2],
["prestigiacomo stefania", 2],
["prestipino patrizia", 2],
["pretto erik umberto", 2],
["prisco emanuele", 2],
["provenza nicola", 2],
["quartapelle procopio lia", 2],
["racchella germano", 2],
["raciti fausto", 2],
["raduzzi raphael", 2],
["raffa angela", 2],
["raffaelli elena", 2],
["rampelli fabio", 2],
["ravetto laura", 2],
["ribolla alberto", 2],
["ricciardi riccardo", 2],
["ripani elisabetta", 2],
["rixi edoardo", 2],
["rizzetto walter", 2],
["rizzo gianluca", 2],
["rizzone marco", 2],
["rizzo nervo luca", 2],
["romaniello cristian", 2],
["romano andrea", 2],
["romano paolo nicolo'", 2],
["rosato ettore", 2],
["rospi gianluca", 2],
["rossello cristina", 2],
["rossi andrea", 2],
["rossini emanuela", 2],
["rossini roberto", 2],
["rosso roberto", 2],
["rostan michela", 2],
["rotelli mauro", 2],
["rotondi gianfranco", 2],
["rotta alessia", 2],
["ruffino daniela", 2],
["ruggieri andrea", 2],
["ruggiero francesca anna", 2],
["ruocco carla", 2],
["russo giovanni", 2],
["russo paolo", 2],
["saccani jotti gloria", 2],
["saitta eugenio", 2],
["salafia angela", 2],
["saltamartini barbara", 2],
["sangregorio eugenio", 2],
["sani luca", 2],
["sapia francesco", 2],
["sarli doriana", 2],
["sarro carlo", 2],
["sarti giulia", 2],
["sasso rossano", 2],
["savino elvira", 2],
["savino sandra", 2],
["scagliusi emanuele", 2],
["scalfarotto ivan", 2],
["scanu lucia", 2],
["scerra filippo", 2],
["schiro' angela", 2],
["schullian manfred", 3],
["scoma francesco", 2],
["scutella' elisa", 2],
["segneri enrica", 2],
["sensi filippo", 2],
["serracchiani debora", 3],
["serritella davide", 2],
["sessa rossella", 2],
["siani paolo", 2],
["sibilia carlo", 2],
["sibilia cosimo", 2],
["silli giorgio", 2],
["silvestri francesco", 2],
["silvestri rachele", 2],
["silvestroni marco", 2],
["siracusano matilde", 2],
["siragusa elisa", 2],
["sisto francesco paolo", 2],
["snider silvana", 2],
["sodano michele", 2],
["sorte alessandro", 2],
["soverini serse", 2],
["sozzani diego", 2],
["spadafora vincenzo", 2],
["spadoni maria edera", 2],
["spena maria", 2],
["spessotto arianna", 2],
["sportiello gilda", 2],
["squeri luca", 2],
["stefani alberto", 2],
["stumpo nicola", 2],
["suriano simona", 2],
["sut luca", 2],
["sutto mauro", 2],
["tarantino leonardo", 2],
["tartaglione annaelsa", 2],
["tasso antonio", 2],
["tateo anna rita", 2],
["termini guia", 2],
["terzoni patrizia", 2],
["testamento rosa alba", 2],
["timbro maria flavia", 2],
["tiramani paolo", 2],
["toccafondi gabriele", 2],
["toccalini luca", 2],
["tofalo angelo", 2],
["tomasi maura", 2],
["tombolato giovanni battista", 2],
["tondo renzo", 2],
["tonelli gianni", 2],
["too raffaele", 2],
["torromino sergio", 2],
["torto daniela", 2],
["trancassini paolo", 2],
["trano raffaele", 2],
["traversi roberto", 2],
["tripiedi davide", 2],
["tripodi elisa", 2],
["tripodi maria", 2],
["trizzino giorgio", 2],
["troiano francesca", 2],
["tucci riccardo", 2],
["turri roberto", 2],
["tuzi manuel", 2],
["ungaro massimo", 2],
["vacca gianluca", 2],
["valbusa vania", 2],
["valente simone", 2],
["valentini valentino", 2],
["vallascas andrea", 2],
["vallotto sergio", 2],
["varchi maria carolina", 2],
["varrica adriano", 2],
["vazio franco", 2],
["verini walter", 2],
["versace giuseppina", 2],
["vianello giovanni", 2],
["vietina simona", 2],
["vignaroli stefano", 2],
["villani virginia", 2],
["villarosa alessio mattia", 2],
["vinci gianluca", 2],
["viscomi antonio", 2],
["vitiello catello", 2],
["vito elio", 2],
["viviani lorenzo", 2],
["vizzini gloria", 2],
["volpi leda", 2],
["volpi raffaele", 2],
["an alessandro", 2],
["zanella federica", 2],
["zanettin pierantonio", 2],
["zangrillo paolo", 2],
["zanichelli davide", 2],
["zanotelli giulia", 2],
["zardini diego", 2],
["zennaro antonio", 2],
["zicchieri francesco", 2],
["ziello edoardo", 2],
["zoffili eugenio", 2],
["zolezzi alberto", 2],
["zordan adolfo", 2],
["zucconi riccardo", 2],
["abate", 4],
["accoto", 4],
["agostinelli", 4],
["aimi", 4],
["airola", 4],
["alberti casellati", 4],
["alderisi", 4],
["alessandrini", 4],
["alfieri", 4],
["anastasi", 4],
["angrisani", 4],
["arrigoni", 4],
["astorre", 4],
["auddino", 4],
["augussori", 4],
["bagnai", 4],
["balboni", 4],
["barachini", 4],
["barbaro", 4],
["barboni", 4],
["battistoni", 4],
["bellanova", 4],
["berardi", 4],
["bergesio", 4],
["bernini", 5],
["berutti", 4],
["biasotti", 4],
["binetti", 4],
["bini", 4],
["biti", 4],
["boccardi", 4],
["boldrini", 4],
["bongiorno", 4],
["bonifazi", 4],
["bonino", 4],
["borghesi", 4],
["borgonzoni", 4],
["bossi", 4],
["bossi", 4],
["bottici", 4],
["botto", 4],
["bressa", 4],
["briziarelli", 4],
["bruzzone", 4],
["buccarella", 4],
["calandrini", 4],
["calderoli", 4],
["caliendo", 4],
["caligiuri", 4],
["campagna", 4],
["campari", 4],
["candiani", 4],
["candura", 4],
["cangini", 4],
["cantu'", 4],
["carbone", 4],
["casolati", 4],
["castaldi", 4],
["castellone", 5],
["castiello", 4],
["catalfo", 4],
["cattaneo", 4],
["causin", 4],
["centinaio", 4],
["cerno", 4],
["cesaro", 4],
["ciampolillo", 4],
["cioffi", 4],
["ciriant", 4],
["cirinna:", 4],
["collina", 4],
["coltorti", 4],
["comincini", 4],
["conzatti", 4],
["corbetta", 4],
["corrado", 4],
["corti", 4],
["craxi", 4],
["crimi", 4],
["croatti", 4],
["crucioli", 4],
["cucca", 4],
["dal mas", 4],
["d'alfonso", 4],
["damiani", 4],
["d'angelo", 4],
["d'arienzo", 4],
["de bertoldi", 4],
["de bonis", 4],
["de carlo", 4],
["de falco", 4],
["de lucia", 4],
["de petris", 4],
["de poli", 4],
["de siano", 4],
["de vecchis", 4],
["dell'olio", 4],
["dessi'", 4],
["di girolamo", 4],
["di marzio", 4],
["dimicco", 4],
["di nicola", 4],
["di piazza", 4],
["donno", 4],
["doria", 4],
["drago", 4],
["durnwalder", 4],
["endrizzi", 4],
["errant", 4],
["evangelista", 4],
["faggi", 4],
["fantetti", 4],
["faraone", 5],
["fattori", 4],
["fazzolari", 4],
["fazzone", 4],
["fede", 4],
["fedeli", 4],
["fenu", 4],
["ferrara", 4],
["ferrari", 4],
["ffrra771", 4],
["ffrrero", 4],
["ferro", 4],
["floridia", 4],
["floris", 4],
["fregolent", 4],
["fusco", 4],
["galliani", 4],
["gallicchio", 4],
["gallone", 4],
["garavini", 4],
["garner santanche'", 4],
["garruti", 4],
["gasparri", 4],
["gaudiano", 4],
["ghedini", 4],
["giacobbe", 4],
["giammanco", 4],
["giannuzzi", 4],
["giarrusso", 4],
["ginetti", 4],
["giro", 4],
["girotto", 4],
["granato", 4],
["grassi", 4],
["grasso", 4],
["grimani", 4],
["guidolin", 4],
["iannone", 4],
["iori", 4],
["iwobi", 4],
["la mura", 4],
["la pietra", 4],
["la russa", 4],
["l'abbate", 4],
["laforgia", 4],
["laniece", 4],
["laniece", 4],
["lanniittt", 4],
["lanzi", 4],
["tatis", 4],
["trone", 4],
["te771", 4],
["ticheri", 4],
["lomutt", 4],
["lonardo", 4],
["lorefice", 4],
["lucidi", 4],
["lunesu", 4],
["lupo", 4],
["maffoni", 4],
["magorno", 4],
["maiorino", 4],
["malan", 4],
["mallegni", 4],
["malpezzi", 5],
["manca", 4],
["mangialavori", 4],
["mantero", 4],
["mantovani", 4],
["marcucci", 4],
["margiotta", 4],
["marilotti", 4],
["marin", 5],
["marinello", 4],
["marino", 4],
["martelli", 4],
["marti", 4],
["masini", 4],
["matrisciano", 4],
["mautone", 4],
["merlo", 4],
["messina", 4],
["messina", 4],
["minasi", 4],
["mininno", 4],
["mirabelli", 4],
["mistant", 4],
["modena", 4],
["moles", 4],
["mollame", 4],
["montani", 4],
["montevecchi", 4],
["monti", 4],
["moronese", 4],
["morra", 4],
["nannicini", 4],
["napolitano", 4],
["nastri", 4],
["naturale", 4],
["nencini", 4],
["nisini", 4],
["nocerino", 4],
["nugnes", 4],
["ortis", 4],
["ostellari", 4],
["pacifico", 4],
["pagano", 4],
["papatheu", 4],
["parente", 4],
["paroli", 4],
["parrini", 4],
["pavanelli", 4],
["pazzaglini", 4],
["pellegrini", 4],
["pellegrini", 4],
["pepe", 4],
["pergreffi", 4],
["perilli", 4],
["perosino", 4],
["pesco", 4],
["petrenga", 4],
["petrocelli", 4],
["pianasso", 4],
["piarulli", 4],
["pichetto fratin", 4],
["pillon", 4],
["pinotti", 4],
["pirovano", 4],
["pirro", 4],
["pisani", 4],
["pisant", 4],
["pittella", 4],
["pittoni", 4],
["pizzol", 4],
["porta", 4],
["presutto", 4],
["pucciarelli", 4],
["puglia", 4],
["ouagliariello", 4],
["ouarto", 4],
["rampi", 4],
["rauti", 4],
["riccardi", 4],
["ricciardi", 4],
["richetti", 4],
["ripamonti", 4],
["rivolta", 4],
["rizzotti", 4],
["rojc", 4],
["romagnoli", 4],
["romani", 4],
["romano", 4],
["romeo", 5],
["ronzulli", 4],
["rossi", 4],
["rossomando", 4],
["rufa", 4],
["ruotolo", 4],
["ruspandini", 4],
["russo", 4],
["saccone", 4],
["santangelo", 4],
["santillo", 4],
["saponara", 4],
["sbrana", 4],
["sbrollini", 4],
["schifani", 4],
["sciascia", 4],
["segre", 4],
["serafini", 4],
["siclari", 4],
["sileri", 4],
["siri", 4],
["stabile", 4],
["stefano", 4],
["steger", 4],
["sudano", 4],
["taricco", 4],
["taverna", 4],
["testor", 4],
["tiraboschi", 4],
["toffanin", 4],
["toninelli", 4],
["tosato", 4],
["totaro", 4],
["trentacoste", 4],
["turco", 4],
["unterberger", 5],
["urraro", 4],
["urso", 4],
["vaccaro", 4],
["valente", 4],
["vallardi", 4],
["vanin", 4],
["vattuone", 4],
["verducci", 4],
["vescovi", 4],
["vitali", 4],
["vono", 4],
["zaffini", 4],
["zanda", 4],
["zuliani", 4],
["bianchi patrizio", 30],
["bonetti elena", 30],
["brunetta renato", 30],
["cartabia marta", 30],
["carfagna mara", 30],
["cingolani roberto", 30],
["cola vittorio", 30],
["dadone fabiana", 30],
["d'inca federico", 30],
["di maio luigi", 30],
["franceschini dario", 30],
["franco daniele", 30],
["garavaglia massimo", 30],
["gerlimi maria stella", 30],
["giorgetti giancarlo", 30],
["giovannini enrico", 30],
["guerini lorenzo", 30],
["lamorgese luciana", 30],
["messa cristina", 30],
["orlando andrea", 30],
["patuanelli stefano", 30],
["speranza roberto", 30],
["stefani erika", 30],
["abramo sergio", 20],
["allevi dario", 20],
["barbieri patrizia", 20],
["bennardi domenico", 20],
["biffoni matteo", 20],
["bindi pierluigi", 20],
["borgna federico", 20],
["bottaro amedeo/bruno giovanna", 20],
["brugnaro luigi", 20],
["brunetti paolo", 20],
["bucci marco", 20],
["calcinaro paolo", 20],
["campus nanni", 20],
["canelli alessandro", 20],
["caramaschi renzo", 20],
["cardellicchio vincenzo", 20],
["caruso franz", 20],
["casanova sara", 20],
["cassi giuseppe", 20],
["castrataro piero", 20],
["cicchetti antonio", 20],
["ciriani alessandro", 20],
["coletta damiano", 20],
["conte mario", 20],
["conti michele", 20],
["corradino claudio", 20],
["corsaro andrea", 20],
["cuttica di revigliasco gianfranco", 20],
["d'alberto gianguido", 20],
["de luca cateno", 20],
["de mossi luigi", 20],
["de pascale michele", 20],
["decaro antonio", 20],
["del bono emilio", 20],
["dipiazza roberto", 20],
["dipietro maurizio", 20],
["fabbri alan", 20],
["ferrara diego", 20],
["festa gianluca", 20],
["fioravanti marco", 20],
["fontanini pietro", 20],
["fracassi fabrizio", 20],
["gaffeo edoardo", 20],
["galiberti gianluca", 20],
["galimberti davide", 20],
["gambino roberto", 20],
["gattiloni mauro", 20],
["ghinelli alessandro", 20],
["giordani sergio", 20],
["gori giorgio", 20],
["gravina roberto", 20],
["gualtieri roberto", 20],
["guarente mario", 20],
["ianaselli franco", 20],
["italia francesco", 20],
["landriscina mario", 20],
["latini leonardo", 20],
["lepore matteo", 20],
["limardo maria", 20],
["lo russo stefano", 20],
["lutzu andrea", 20],
["mancinelli valeria", 20],
["manfredi gaetano", 20],
["marchionini silvia", 20],
["marino carlo", 20],
["masci carlo", 20],
["massaro jacopo", 20],
["mastella clemente", 20],
["miccichè francesco", 20],
["morittu pietro", 20],
["muzzarelli gian carlo", 20],
["napoli vincenzo", 20],
["nardella dario", 20],
["nuti gianni", 20],
["orlando leoluca", 20],
["ottaviani nicola", 20],
["palazzi mattia", 20],
["parcaroli sandro", 20],
["peraccini pierluigi", 20],
["persiani francesco", 20],
["pizzarotti federico", 20],
["pogliese salvo", 20],
["rasero maurizio", 20],
["ricci matteo", 20],
["romizi andrea", 20],
["rossi ricardo", 20],
["rucco francesco", 20],
["russo marco", 20],
["sadegholvaad jamil", 20],
["sala giuseppe", 20],
["salvemini carlo", 20],
["salvetti luca", 20],
["sboarina federico", 20],
["scajola claudio", 20],
["scarameillini marco", 20],
["scolamiero antonella", 20],
["soddu andrea", 20],
["tambellini alessandro", 20],
["tomasi alessandro", 20],
["tranchida giacomo", 20],
["truzzu paolo", 20],
["vecchi luca", 20],
["vivarelli colonna antonfrancesco", 20],
["voce vincenzo", 20],
["zattini gian luca", 20],
["ziberna rodolfo", 20],
["acouaroli francesco", 20],
["bardi vito", 20],
["bonaccini stefano", 20],
["cirio alberto", 20],
["de luca vincenzo", 20],
["emiliano michele", 20],
["fedriga massimiliano", 20],
["fontana attilio", 20],
["fugatti maurizio", 20],
["giani eugenio", 20],
["lavevaz erik", 20],
["marsilio marco", 20],
["musumeci nello", 20],
["occhiuto roberto", 20],
["solinas christian", 20],
["tesei donatella", 20],
["toma donato", 20],
["zaia luca", 20],
["zingaretti nicola", 20],
["draghi mario", 50],
["meloni giorgia", 50],
["letta enrico", 50],
["salvini matteo", 50],
["berlusconi silvio", 50],
["conte giuseppe", 50],
["calenda carlo", 50],
["renzi matteo", 50],
["adinolfi mario", 50],
["brignone beatrice", 50],
["brugnaro luigi", 50],
["casini pier ferdinando", 50],
["collot marta", 50],
["de magistris luigi", 50],
["della vedova benedetto", 50],
["fratoianni nicola", 50],
["lupi maurizio", 50],
["paragon gianluigi", 50],
["rizzo marco", 50],
["sgarbi vittorio", 50],
["tabacci bruno", 50],
["tosi flavio", 50],
["toti giovanni", 50],
]
