var giocatori = [
["acunzo nicola", 2],
["adelizzi cosimo", 2],
["aiello davide", 2],
["aiello piera", 2],
["alaimo roberta", 2],
["albano lucia", 2],
["alemanno maria soave", 2],
["amitrano alessandro", 2],
["andreuzza giorgia", 2],
["angelucci antonio", 2],
["angiola nunzio", 2],
["annibali lucia", 2],
["anzaldi michele", 2],
["aprea valentina", 2],
["aprile nadia", 2],
["aresta giovanni luca", 2],
["ascani anna", 2],
["ascari stefania", 2],
["avossa eva", 2],
["azzolina lucia", 2],
["badole mirco", 2],
["bagnasco roberto", 2],
["baldelli simone", 2],
["baldini maria teresa", 2],
["baldino vittoria", 2],
["baratto raffaele", 2],
["barbuto elisabetta maria", 2],
["barelli paolo", 3],
["baroni anna lisa", 2],
["baroni massimo enrico", 2],
["bartolozzi giusi", 2],
["barzotti valentina", 2],
["basin giuseppe", 2],
["battelli sergio", 2],
["battilocchio alessandro", 2],
["bazoli alfredo", 2],
["bazzaro alex", 2],
["bella marco", 2],
["bellachioma giuseppe ercole", 2],
["bellucci maria teresa", 2],
["belotti daniele", 2],
["benamati gianluca", 2],
["bendinelli davide", 2],
["benedetti silvia", 2],
["benigni stefano", 2],
["benvenuto alessandro manuel", 2],
["berardini fabio", 2],
["bergamini deborah", 2],
["berlinghieri marina", 2],
["bersani pier luigi", 2],
["berti francesco", 2],
["bianchi matteo luigi", 2],
["biancofiore michaela", 2],
["bignami galeazzo", 2],
["billi simone", 2],
["bilotti anna", 2],
["binelli diego", 2],
["bisa ingrid", 2],
["bitonci massimo", 2],
["[boccia francesco", 2],
["boldi rossana", 2],
["boldrini laura", 2],
["bologna fabiola", 2],
["bonafede alfonso", 2],
["bond dario", 2],
["boniardi fabio massimo", 2],
["bonomo francesca", 2],
["bordo michele", 2],
["bordonali simona", 2],
["borghese mario alejandro", 2],
["borghi claudio", 2],
["borghi enrico", 2],
["boschi maria elena", 3],
["braga chiara", 2],
["brambilla michela vittoria", 2],
["brescia giuseppe", 2],
["bruno raffaele", 2],
["bruno bossio vincenza", 2],
["bubisutti aurelia", 2],
["bucalo carmela", 2],
["buffagni stefano", 2],
["buompane giuseppe", 2],
["buratti umberto", 2],
["businarolo francesca", 2],
["butti alessio", 2],
["cabras pino", 2],
["cadeddu luciano", 2],
["caffaratto gualtiero", 2],
["caiata salvatore", 2],
["calabria annagrazia", 2],
["campana micaela", 2],
["cancelleri azzurra pia maria", 2],
["cannatelli pasquale", 2],
["cannizzaro francesco", 2],
["cantalamessa gianluca", 2],
["cantini laura", 2],
["cantone carla", 2],
["cantone luciano", 2],
["caon roberto", 2],
["caparvi virginio", 2],
["capitanio massimiliano", 2],
["cappellacciugo", 2],
["cappellani santi", 2],
["carabetta luca", 2],
["carbonaro alessandra", 2],
["cardinale daniela", 2],
["care' nicola", 2],
["carelli emilio", 2],
["caretta maria cristina", 2],
["carinelli paola", 2],
["carnevali elena", 2],
["carrara maurizio", 2],
["casa vittoria", 2],
["casciello luigi", 2],
["casino michele", 2],
["caso andrea", 2],
["cassese gianpaolo", 2],
["cassinelli roberto", 2],
["castelli laura", 2],
["castiello giuseppina", 2],
["casu andrea", 2],
["cataldi roberto", 2],
["cattaneo alessandro", 2],
["cattoi maurizio", 2],
["cattoi vanessa", 2],
["cavandoli laura", 2],
["ceccanti stefano", 2],
["cecchetti fabrizio", 2],
["cecconi andrea", 2],
["cenni susanna", 2],
["centemero giulio", 2],
["cestari emanuele", 2],
["chiazzese giuseppe", 2],
["ciaburro monica", 2],
["ciaga' graziella levla", 2],
["ciampi lucia", 2],
["cillis luciano", 2],
["cimino rosalba", 2],
["ciprinitiziana", 2],
["cirielli edmondo", 2],
["coin dimitri", 2],
["colaninno matteo", 2],
["colla jari", 2],
["colletti andrea", 2],
["colmellere angela", 2],
["colucci alessandro", 2],
["comaroli silvan andreina", 2],
["comencini vito", 2],
["cominardi claudio", 2],
["conte federico", 2],
["corda emanuela", 2],
["cornel valentina", 2],
["cortelazzo piergiorgio", 2],
["costa enrico", 2],
["costanzo jessica", 2],
["covolo silvia", 2],
["crippa andrea", 3],
["crippa davide", 3],
["cristina mirella", 2],
["critelli francesco", 2],
["cubeddu sebastiano", 2],
["cunial sara", 2],
["curro' giovanni", 2],
["daga federica", 2],
["d'alessandro camillo", 2],
["dall'osso matteo", 2],
["dal moro gian pietro", 2],
["d'ambrosio giuseppe", 2],
["dara andrea", 2],
["d'arrando celeste", 2],
["d'attis mauro", 2],
["/ de angelis sara", 2],
["de carlo sabrina", 2],
["de filippo vito", 2],
["de giorgi rosalba", 2],
["de girolamo carlo ügo", 2],
["deiana paola", 2],
["deidda salvatore", 2],
["del barba mauro", 2],
["del basso de caro umberto", 2],
["del grosso daniele", 2],
["d'elia cecilia", 2],
["della frera guido", 2],
["delmastro delle vedove andrea", 2],
["del monaco antonio", 2],
["de lorenzis diego", 2],
["de lorenzo rina", 2],
["delrio graziano", 2],
["del sesto margherita", 2],
["de luca piero", 2],
["de maria andrea", 2],
["de martini guido", 2],
["de menech roger", 2],
["de micheli paola", 2],
["d'eramo luigi", 2],
["de toma massimiliano", 2],
["d'ettore felice maurizio", 2],
["dieni federica", 2],
["di giorgi rosa maria", 2],
["dilauro carmen", 2],
["di maio marco", 2],
["di muro flavio", 2],
["d'ippolito giuseppe", 2],
["di san martino lorenzato di ivrea luis", 2],
["roberto", 2],
["di sarno gianfranco", 2],
["di stasio iolanda", 2],
["di stefano manlio", 2],
["donina giuseppe cesare", 2],
["donno leonardo", 2],
["donzelli giovanni", 2],
["dori devis", 2],
["d'orso valentina", 2],
["durigon claudio", 2],
["d'uva francesco", 2],
["ehm yana chiara", 2],
["emiliozzi mirella", 2],
["ermellino alessandra", 2],
["fantinati mattia", 2],
["fantuz marica", 2],
["faro marialuisa", 2],
["fascina marta antonia", 2],
["fassina stefano", 2],
["fassino piero", 2],
["fatuzzo carlo", 2],
["federico antonio", 2],
["ferraili marzia", 2],
["ferraresi vittorio", 2],
["ferrari roberto paolo", 2],
["ferri cosimo maria", 2],
["ferro wanda", 2],
["fiano emanuele", 2],
["ficara paolo", 2],
["fico roberto", 10],
["fioramonti lorenzo", 2],
["fiorini benedetta", 2],
["fitzgerald nissoli fucsia", 2],
["fl.ati francesca", 2],
["fogliani ketty", 2],
["fontana gregorio", 2],
["fontana ilaria", 2],
["fontana lorenzo", 2],
["forciniti francesco", 2],
["formentini paolo", 2],
["fornaro federico", 3],
["foscolo sara", 2],
["i foti tommaso", 2],
["fraccaro riccardo", 2],
["fragomeli gian mario", 2],
["frailis andrea", 2],
["frassinetti paola", 2],
["frassini rebecca", 2],
["frate flora", 2],
["fregolent silvia", 2],
["frusone luca", 2],
["furgiuele domenico", 2],
["fusacchia alessandro", 2],
["gadda maria chiara", 2],
["gagliardi manuela", 2],
["gagnarli chiara", 2],
["galantino davide", 2],
["galizia francesca", 2],
["galli dario", 2],
["gallinella filippo", 2],
["gallo luigi", 2],
["gariglio davide", 2],
["gastaldi flavio", 2],
["gava vannia", 2],
["gebhard renate", 2],
["gemmato marcello", 2],
["gentile andrea", 2],
["gerardi francesca", 2],
["germana' antonino", 2],
["giaccone andrea", 2],
["giachetti roberto", 2],
["giacometti antonietta", 2],
["giacometto carlo", 2],
["giacomoni sestino", 2],
["giannone veronica", 2],
["giarrizzo andrea", 2],
["giglio vigna alessandro", 2],
["giordano conny", 2],
["giorgis andrea", 2],
["giuliano carla", 2],
["giuliodori paolo", 2],
["gobbato claudia", 2],
["golinelli guglielmo", 2],
["grande marta", 2],
["gribaudo chiara", 2],
["grillo giulia", 2],
["grimaldi nicola", 2],
["grimoldi paolo", 2],
["grippa carmela", 2],
["gubitosa michele", 2],
["gusmeroli alberto luigi", 2],
["ianaro angela", 2],
["iezzi igor giancarlo", 2],
["incerti antonella", 2],
["invernizzi cristian", 2],
["invidia niccolo'", 2],
["iorio marianna", 2],
["iovino luigi", 2],
["l'abbate giuseppe", 2],
["labriola vincenza", 2],
["lacarra marco", 2],
["la marca francesca", 2],
["lapia mara", 2],
["lattanzio paolo", 2],
["lazzarini arianna", 2],
["legnaioli donatella", 2],
["lepri stefano", 2],
["librandi gianfranco", 2],
["licatini caterina", 2],
["liuni marzio", 2],
["liuzzi mirella", 2],
["lolini mario", 2],
["lollobrigida francesco", 3],
["lombardo antonio", 2],
["lo monte carmelo", 2],
["longo fausto", 2],
["lorefice marialucia", 2],
["lorenzin beatrice", 2],
["lorenzoni eva", 2],
["lorenzoni gabriele", 2],
["losacco alberto", 2],
["loss martina", 2],
["lotti luca", 2],
["lovecchio giorgio", 2],
["lucaselli ylenja", 2],
["lucchini elena", 2],
["lucentini mauro", 2],
["maccanti elena", 2],
["macina anna", 2],
["madia maria anna", 2],
["maggioni marco", 2],
["magi riccardo", 2],
["maglione pasquale", 2],
["mammi' stefania", 2],
["manca alberto", 2],
["manca gavino", 2],
["mancini claudio", 2],
["mandelli andrea", 2],
["maniero alvise", 2],
["mantovani lucrezia maria benedetta", 2],
["manzato franco", 2],
["manzo teresa", 2],
["maraia generoso", 2],
["marattin luigi", 2],
["marchetti ricardo augusto", 2],
["mariani felice", 2],
["marin marco", 3],
["marino bernardo", 2],
["marrocco patrizia", 2],
["martinciglio vita", 2],
["martin antonio", 2],
["marzana maria", 2],
["maschio ciro", 2],
["masi angela", 2],
["maturi filippo", 2],
["mauri matteo", 2],
["mazzetti erica", 2],
["melicchio alessandro", 2],
["melilli fabio", 2],
["menga rosa", 2],
["miceli carmelo", 2],
["micheli matteo", 2],
["micillo salvatore", 2],
["migliore gennaro", 2],
["migliorino luca", 2],
["milanato lorena", 2],
["minardo antonino", 2],
["misiti carmelo massimo", 2],
["molinari riccardo", 3],
["mollicone federico", 2],
["molten nicola", 2],
["montaruli augusta", 2],
["mor mattia", 2],
["morani alessia", 2],
["morassut roberto", 2],
["morelli alessandro", 2],
["moretto sara", 2],
["morgoni mario", 2],
["morrone jacopo", 2],
["moschioni daniele", 2],
["mugnai stefano", 2],
["mule' giorgio", 2],
["mura romina", 2],
["murelli elena", 2],
["muroni rossella", 2],
["musella graziano", 2],
["napoli osvaldo", 2],
["nappi silvana", 2],
["nardi martina", 2],
["navarra pietro", 2],
["nesci dalila", 2],
["nevi raffaele", 2],
["nitti michele", 2],
["nobili luciano", 2],
["noja lisa", 2],
["novelli roberto", 2],
["occhionero giuseppina", 2],
["olgiati riccardo", 2],
["orfini matteo", 2],
["orrico anna laura", 2],
["orsini andrea", 2],
["osnato marco", 2],
["pagani alberto", 2],
["pagan alessandro", 2],
["pagano ubaldo", 2],
["paita raffaella", 2],
["palazzotto erasmo", 2],
["pallini maria", 2],
["palmier antonio", 2],
["palmisano valentina", 2],
["panizzut massimiliano", 2],
["paolin giuseppe", 2],
["paolini luca rodolfo", 2],
["papiro antonella", 2],
["parentela paolo", 2],
["parisse martina", 2],
["parolo ugo", 2],
["pastorino luca", 2],
["patassini tullio", 2],
["patelli cristina", 2],
["paternoster paolo", 2],
["paxia maria laura", 2],
["pedrazzini claudio", 2],
["pella roberto", 2],
["pellicani nicola", 2],
["penna leonardo salvatore", 2],
["pentangelo antonio", 2],
["perantoni mario", 2],
["perconti filippo giuseppe", 2],
["perego di cremnago matteo", 2],
["pettarin guido germano", 2],
["pettazzi lino", 2],
["pezzopane stefania", 2],
["piastra carlo", 2],
["picchi guglielmo", 2],
["piccoli nardelli flavia", 2],
["piccolo tiziana", 2],
["pignatone dedalo cosimo gaetano", 2],
["pini giuditta", 2],
["pittalis pietro", 2],
["pizzetti luciano", 2],
["plangger albrecht", 2],
["polidori catia", 2],
["pollastrini barbara", 2],
["polverini renata", 2],
["porchietto claudia", 2],
["portas giacomo", 2],
["potenti manfredi", 2],
["prestigiacomo stefania", 2],
["prestipino patrizia", 2],
["pretto erik umberto", 2],
["prisco emanuele", 2],
["provenza nicola", 2],
["quartapelle procopio lia", 2],
["racchella germano", 2],
["raciti fausto", 2],
["raduzzi raphael", 2],
["raffa angela", 2],
["raffaelli elena", 2],
["rampelli fabio", 2],
["ravetto laura", 2],
["ribolla alberto", 2],
["ricciardi riccardo", 2],
["ripani elisabetta", 2],
["rixi edoardo", 2],
["rizzetto walter", 2],
["rizzo gianluca", 2],
["rizzone marco", 2],
["rizzo nervo luca", 2],
["romaniello cristian", 2],
["romano andrea", 2],
["romano paolo nicolo'", 2],
["rosato ettore", 2],
["rospi gianluca", 2],
["rossello cristina", 2],
["rossi andrea", 2],
["rossini emanuela", 2],
["rossini roberto", 2],
["rosso roberto", 2],
["rostan michela", 2],
["rotelli mauro", 2],
["rotondi gianfranco", 2],
["rotta alessia", 2],
["ruffino daniela", 2],
["ruggieri andrea", 2],
["ruggiero francesca anna", 2],
["ruocco carla", 2],
["russo giovanni", 2],
["russo paolo", 2],
["saccani jotti gloria", 2],
["saitta eugenio", 2],
["salafia angela", 2],
["saltamartini barbara", 2],
["sangregorio eugenio", 2],
["sani luca", 2],
["sapia francesco", 2],
["sarli doriana", 2],
["sarro carlo", 2],
["sarti giulia", 2],
["sasso rossano", 2],
["savino elvira", 2],
["savino sandra", 2],
["scagliusi emanuele", 2],
["scalfarotto ivan", 2],
["scanu lucia", 2],
["scerra filippo", 2],
["schiro' angela", 2],
["schullian manfred", 3],
["scoma francesco", 2],
["scutella' elisa", 2],
["segneri enrica", 2],
["sensi filippo", 2],
["serracchiani debora", 3],
["serritella davide", 2],
["sessa rossella", 2],
["siani paolo", 2],
["sibilia carlo", 2],
["sibilia cosimo", 2],
["silli giorgio", 2],
["silvestri francesco", 2],
["silvestri rachele", 2],
["silvestroni marco", 2],
["siracusano matilde", 2],
["siragusa elisa", 2],
["sisto francesco paolo", 2],
["snider silvana", 2],
["sodano michele", 2],
["sorte alessandro", 2],
["soverini serse", 2],
["sozzani diego", 2],
["spadafora vincenzo", 2],
["spadoni maria edera", 2],
["spena maria", 2],
["spessotto arianna", 2],
["sportiello gilda", 2],
["squeri luca", 2],
["stefani alberto", 2],
["stumpo nicola", 2],
["suriano simona", 2],
["sut luca", 2],
["sutto mauro", 2],
["tarantino leonardo", 2],
["tartaglione annaelsa", 2],
["tasso antonio", 2],
["tateo anna rita", 2],
["termini guia", 2],
["terzoni patrizia", 2],
["testamento rosa alba", 2],
["timbro maria flavia", 2],
["tiramani paolo", 2],
["toccafondi gabriele", 2],
["toccalini luca", 2],
["tofalo angelo", 2],
["tomasi maura", 2],
["tombolato giovanni battista", 2],
["tondo renzo", 2],
["tonelli gianni", 2],
["too raffaele", 2],
["torromino sergio", 2],
["torto daniela", 2],
["trancassini paolo", 2],
["trano raffaele", 2],
["traversi roberto", 2],
["tripiedi davide", 2],
["tripodi elisa", 2],
["tripodi maria", 2],
["trizzino giorgio", 2],
["troiano francesca", 2],
["tucci riccardo", 2],
["turri roberto", 2],
["tuzi manuel", 2],
["ungaro massimo", 2],
["vacca gianluca", 2],
["valbusa vania", 2],
["valente simone", 2],
["valentini valentino", 2],
["vallascas andrea", 2],
["vallotto sergio", 2],
["varchi maria carolina", 2],
["varrica adriano", 2],
["vazio franco", 2],
["verini walter", 2],
["versace giuseppina", 2],
["vianello giovanni", 2],
["vietina simona", 2],
["vignaroli stefano", 2],
["villani virginia", 2],
["villarosa alessio mattia", 2],
["vinci gianluca", 2],
["viscomi antonio", 2],
["vitiello catello", 2],
["vito elio", 2],
["viviani lorenzo", 2],
["vizzini gloria", 2],
["volpi leda", 2],
["volpi raffaele", 2],
["an alessandro", 2],
["zanella federica", 2],
["zanettin pierantonio", 2],
["zangrillo paolo", 2],
["zanichelli davide", 2],
["zanotelli giulia", 2],
["zardini diego", 2],
["zennaro antonio", 2],
["zicchieri francesco", 2],
["ziello edoardo", 2],
["zoffili eugenio", 2],
["zolezzi alberto", 2],
["zordan adolfo", 2],
["zucconi riccardo", 2],
]
